server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: lb://catalog
          predicates:
            - Path=/catalog/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/order/**
        - id: inventory
          uri: lb://inventory
          predicates:
            - Path=/inventory/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
